### PR TITLE
Add alpn support

### PR DESCRIPTION
**Pull request by rasztasd**
Hello!

I have added support for setting the alpn in the ssl connection. This feature is required for Nokia for a use case. This can be useful for anyone using stunnel.

If documentation update or example config file is needed, then please let me know.

Br, Dani

### CODE REVIEW

**Comment by mtrojnar** [comment]
I don't accept 3rd party patches.

**Comment by rasztasd** [comment]
Thank you for the answer. Does it mean you will never accept any pull requests?

**Comment by mtrojnar** [comment]
This repository is based on public releases to make it easier for others to make their own forks.  The actual repository used for development is private, and only accessible to the development team.  Therefore, pull requests from the public repository are never directly merged to the development repository.

I may sometimes accept a patch, which could be based on a pull request to the public repository.  The conditions are:

- Non-copyleft license for the patch (preferably, freeware).
- Sufficiently high code quality.

More often I implement (or re-implement) ideas provided by the users (or paying customers) by myself.  You can search https://www.stunnel.org/NEWS.html for the word "sponsored" in order to find features I implemented for paying customers.  See https://www.stunnel.org/support.html for additional details about our support levels.

**Comment by rasztasd** [comment]
Hello Mtrojnar! Sorry for bothering you again. I juts want to add some informations to the PR, so you might reconsider accepting it.

I based the implementation on the openssl's reference app code:

The definition of parse protos:
https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/apps/apps.c#L1977
https://github.com/mtrojnar/stunnel/pull/17/commits/fe482ca95620853b56e670a28d25e2a1b5d14d7c#diff-d3828aa6baceee8062d82ae8a4eae7c08491d593a69a3253882fb11c710ec81cR142

Set alpn in ssl context:
https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/apps/s_client.c#L1878
https://github.com/mtrojnar/stunnel/pull/17/commits/fe482ca95620853b56e670a28d25e2a1b5d14d7c#diff-d3828aa6baceee8062d82ae8a4eae7c08491d593a69a3253882fb11c710ec81cR286

When it was necessary I changed some minor differences here and there, for example error handling. 
https://github.com/mtrojnar/stunnel/pull/17/commits/fe482ca95620853b56e670a28d25e2a1b5d14d7c#diff-d3828aa6baceee8062d82ae8a4eae7c08491d593a69a3253882fb11c710ec81cR286
https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/apps/s_client.c#L1890

**Comment by xwang1498** [comment]
Hi @rasztasd , while it's disappointing that @mtrojnar didn't accept or implement your patch, I just wanted to let you know that I found it quite useful. (I was using stunnel to proxy unencrypted->encrypted gRPC client, which required ALPN support.) Thanks for your efforts!

**Pull request closed without merging**
