### PR TITLE
Add rtengine random support. Add check seed function existence

### PR DESCRIPTION
**Pull request by lo1ol**

### CODE REVIEW

**Comment by mtrojnar** [comment]
Some description or at least references might be useful for those of us who don't work for ФСБ (such as myself).

**Comment by lo1ol** [comment]
Recently, I got a task to configure stunnel client which uses GOST algorithms of authentication and encryption implemented on RuToken. I did it via rtengine, which contains all logic of working with token (including authentication and encryption)

When I finished my work, I noticed, that stunnel can get entropy from OpenSSL engines, also. Rtengine contains interface of got entropy from token. So when I added option of getting entropy from engine, stunnel failed when initializing PRNG.

I started debugging and found that interface of my engine doesn't contain functions for seeding and checking status of seeding. As it turned out, token can generate PRN without seeding (and function of getting status of seeding is odd, consecuently). 

So, I added checking on existence of the functions before initializing PRNG.

Thank you for your response:) 

P.s. not all human who linked with GOST work on ФСБ (such as myself)

**Comment by mtrojnar** [comment]
> stunnel failed when initializing PRNG

1. Do you mean a "PRNG was not seeded with enough random bytes" error, or rather it failed in some other way?
2. Is there a specific reason to check for `meth->seed`?  AFAIK stunnel only uses `meth->add` (at least with a fairly recent OpenSSL).

I think the patch should be something like:
``` patch
@@ -260,6 +260,13 @@ NOEXPORT int compression_init(GLOBAL_OPTIONS *global) {
 NOEXPORT int prng_init(GLOBAL_OPTIONS *global) {
     int totbytes=0;
     char filename[256];
+    const RAND_METHOD *meth=RAND_get_rand_method();
+
+    /* skip PRNG initialization when no seeding methods are available */
+    if(meth->status==NULL || meth->add==NULL) {
+        s_log(LOG_DEBUG, "No PRNG seeding methods");
+        return 0; /* success */
+    }
 
     if(RAND_status()) {
         s_log(LOG_DEBUG, "No PRNG seeding was required");
```

Any comments?

**Comment by lo1ol** [comment]
1. In the log i get message that PRNG was not seeded with enough random bytes". But as fact, i have no interface for initializing at all, because it's unnecessary

2. may be. But I prefer to wrap this cheching in function. And will check for meth->add for future chengings.

**Comment by mtrojnar** [comment]
The change will be included in stunnel 5.56.  Thank you.

**Comment by lo1ol** [comment]
Oooho, thank you!)

**Pull request closed without merging**
