### PR TITLE
Implement "direct" protocol

### PR DESCRIPTION
**Pull request by stavultras**
This patch implements "direct" protocol to support any connections via 1 port or 1 SNI. Uses already exiting "protocolHost" option as a target host. The idea is described here: https://www.stunnel.org/mailman3/hyperkitty/list/stunnel-users@stunnel.org/thread/O6YQPRI3JQJHDZHNTZWV3CFFCAS3G6HM/

Configs would look like:
[server]
accept = 443
protocol = direct

[client_ssh]
client = yes
accept = 44322
protocolHost = 127.0.0.1:22
protocol = direct
connect = server:443

[client_telnet]
client = yes
accept = 44323
protocolHost = 127.0.0.1:23
protocol = direct
connect = server:443

Similar to socks5 protocol, but it doesn't require applications to have socks5 client support.

Usage on client's host: ssh -h 127.0.0.1 -P 44322 or telnet 127.0.0.1:44332.

As you can see here, only 1 port 443 is used for all client connections.

### CODE REVIEW

**Comment by mtrojnar** [comment]
SSH is not a good example either: https://serverfault.com/questions/1050866/is-there-a-built-in-way-to-proxy-ssh-through-socks5

**Comment by stavultras** [comment]
Yeah, i know, but it was the first thing that i could image (since i use it). Telnet is a good example though and all other non-TLS applications, like at the same time, on the same port, without any additions actions, applications or changes: ssh, openvpn tcp, 3proxy, hev-socks5-server (that supports UDP-in-TCP feature. Actually a very good stuff to proxy UDP via TCP (QUIC protocol for an example) via stunnel + hev-socks5-tproxy on a client's host) behind the same port or SNI, and etc.

I'm ok with my local patch, but maybe other people would need it for some other applications using the same server's port or SNI. It affects nothing and makes no harm, technically, to add this protocol.

**Comment by stavultras** [comment]
i recalled that someone asked a question about tunneling UDP via stunnel and you said if there's a solution, please provide - there's the solution: hev-socks5-server (https://github.com/heiher/hev-socks5-server) + hev-socks5-tproxy (https://github.com/heiher/hev-socks5-tproxy):
```
# Socks5 UDP relay mode (tcp|udp)
  udp: 'tcp'
```
in hev-socks5-tproxy settings + iptables' TPROXY rules with "mark" and "ip rule" stuff. I've been using this solution via stunnel for a week without any problems.

**Comment by stavultras** [comment]
Oh, forgot to mention: with "direct" protocol, stunnel could serve as "relay" to other stunnels. Maybe i should have called it "relay" instead of "direct". It make more sense now to me.

**Comment by mtrojnar** [comment]
I think the proper way of implementing such feature would be to make the existing socks client protocol negotiation recognize the "protocolHost" option rather than designing and implementing yet another proprietary protocol.  It's way better for interoperability.

Also, simpler and less error-prone...

**Comment by stavultras** [comment]
Oh, i didn't even think about modifying socks5 client. I will try tomorrow, maybe send DOMAINNAME (socks.req.atyp==0x03) in the header for socks5 server from client and force client to return non-wrapped-to-socks response.

Good idea, thanks.

**Comment by mtrojnar** [comment]
No need to modify the server-side protocol.  A SOCKS server already connects to a given host and port.  I intend to use a functionality that is already there.

I'll implement this feature later this week.

**Comment by stavultras** [comment]
> No need to modify the server-side protocol. A SOCKS server already connects to a given host and port. I intend to use a functionality that is already there.

Yes, I changed my mind (after thinking) and fixed the initial message to use DOMAINNAME (socks.req.atyp==0x03).

> I'll implement this feature later this week.

thank you very much.

**Comment by stavultras** [comment]
Oh, there's only one thing that concerns me:
`if(validate_connect_addr(c)) {`
it won't allow to connect to 127.0.0.1 in a case if you want to use local services...but there's still a workaround, add a virtual interface to the main one with IP, let's say 10.0.0.1, assign needed services to this IP and use it in protocolHost, so, not a big deal for those who would really need it.

**Comment by mtrojnar** [comment]
> Oh, there's only one thing that concerns me: `if(validate_connect_addr(c)) {` it won't allow to connect to 127.0.0.1 in a case if you want to use local services...but there's still a workaround, add a virtual interface to the main one with IP, let's say 10.0.0.1, assign needed services to this IP and use it in protocolHost, so, not a big deal for those who would really need it.

You should consider using a dedicated SOCKS server when running a public service to protect your internal IP addresses (not only loopback) and prevent using the SOCKS service to bypass your firewall rules.  The current code assumes that you control and trust both sides of the connection.  You obviously need mTLS for to ensure that.

**Comment by mtrojnar** [comment]
The implementation:
``` diff
diff --git a/src/protocol.c b/src/protocol.c
index c8c65ea..e2a77ee 100644
--- a/src/protocol.c
+++ b/src/protocol.c
@@ -204,6 +204,9 @@ typedef union {
     struct {
         uint8_t ver, code, rsv, atyp, addr[4], port[2];
     } v4;
+    struct {
+        uint8_t ver, code, rsv, atyp, len, data[255+2]; /* data: name+port */
+    } host;
     struct {
         uint8_t ver, code, rsv, atyp, addr[16], port[2];
     } v6;
@@ -240,31 +243,81 @@ NOEXPORT void socks5_client_address(CLI *c) {
     SOCKADDR_UNION addr;
     SOCKS5_UNION socks;
 
-    if(original_dst(c->local_rfd.fd, &addr))
-        throw_exception(c, 2); /* don't reset */
     memset(&socks, 0, sizeof socks);
     socks.req.ver=5; /* SOCKS5 */
     socks.req.cmd=0x01; /* CONNECT */
-    switch(addr.sa.sa_family) {
-    case AF_INET:
-        socks.req.atyp=0x01; /* IP v4 address */
-        memcpy(&socks.v4.addr, &addr.in.sin_addr, 4);
-        memcpy(&socks.v4.port, &addr.in.sin_port, 2);
-        s_log(LOG_INFO, "Sending SOCKS5 IPv4 address");
-        s_ssl_write(c, &socks, sizeof socks.v4);
-        break;
+
+    if(c->opt->protocol_host) { /* explicit destination */
+        char *tmp_str, *host_str, *port_str;
+        size_t host_len, offset;
+        long port_num;
+
+        /* parse c->opt->protocol_host */
+        socks.req.atyp=0x03; /* DOMAINNAME */
+        tmp_str=strrchr(c->opt->protocol_host, ':');
+        if(tmp_str) {
+            host_str=c->opt->protocol_host;
+            host_len=(size_t)(tmp_str - host_str);
+            port_str=tmp_str+1;
+        } else {
+            host_str="localhost";
+            host_len=strlen(host_str);
+            port_str=c->opt->protocol_host;
+        }
+
+        /* set the host name */
+        if(host_len > 0xff) {
+            s_log(LOG_ERR, "protocolHost too long");
+            throw_exception(c, 2); /* don't reset */
+        }
+        socks.host.len=(uint8_t)host_len;
+        memcpy(socks.host.data, host_str, host_len);
+        offset=host_len;
+
+        /* set the port number */
+        port_num=strtol(port_str, &tmp_str, 10);
+        if(tmp_str==port_str || *tmp_str) { /* not a number */
+            struct servent result_buf, *service;
+            char buffer[1024];
+            int error;
+
+            error=getservbyname_r(port_str, "tcp", &result_buf,
+                buffer, sizeof buffer, &service);
+            if(error || !service) {
+                s_log(LOG_ERR, "Invalid port: %s", port_str);
+                throw_exception(c, 2); /* don't reset */
+            }
+            port_num=ntohs((u_short)service->s_port);
+        }
+        socks.host.data[offset++]=(uint8_t)(port_num>>8); /* MSB */
+        socks.host.data[offset++]=(uint8_t)(port_num&0xff); /* LSB */
+
+        s_log(LOG_INFO, "Sending SOCKS5 DOMAINNAME");
+        s_ssl_write(c, &socks, (int)(offsetof(SOCKS5_UNION, host.data)+offset));
+    } else { /* transparent destination */
+        if(original_dst(c->local_rfd.fd, &addr))
+            throw_exception(c, 2); /* don't reset */
+        switch(addr.sa.sa_family) {
+        case AF_INET:
+            socks.req.atyp=0x01; /* IP v4 address */
+            memcpy(&socks.v4.addr, &addr.in.sin_addr, 4);
+            memcpy(&socks.v4.port, &addr.in.sin_port, 2);
+            s_log(LOG_INFO, "Sending SOCKS5 IPv4 address");
+            s_ssl_write(c, &socks, sizeof socks.v4);
+            break;
 #ifdef USE_IPv6
-    case AF_INET6:
-        socks.req.atyp=0x04; /* IP v6 address */
-        memcpy(&socks.v6.addr, &addr.in6.sin6_addr, 16);
-        memcpy(&socks.v6.port, &addr.in6.sin6_port, 2);
-        s_log(LOG_INFO, "Sending SOCKS5 IPv6 address");
-        s_ssl_write(c, &socks, sizeof socks.v6);
-        break;
+        case AF_INET6:
+            socks.req.atyp=0x04; /* IP v6 address */
+            memcpy(&socks.v6.addr, &addr.in6.sin6_addr, 16);
+            memcpy(&socks.v6.port, &addr.in6.sin6_port, 2);
+            s_log(LOG_INFO, "Sending SOCKS5 IPv6 address");
+            s_ssl_write(c, &socks, sizeof socks.v6);
+            break;
 #endif
-    default:
-        s_log(LOG_ERR, "Unsupported address type 0x%02x", addr.sa.sa_family);
-        throw_exception(c, 2); /* don't reset */
+        default:
+            s_log(LOG_ERR, "Unsupported address type 0x%02x", addr.sa.sa_family);
+            throw_exception(c, 2); /* don't reset */
+        }
     }
 
     s_ssl_read(c, &socks, sizeof socks.resp);
 ````

**Comment by stavultras** [comment]
Thanks! Works like a charm.

**Comment by mtrojnar** [comment]
https://www.stunnel.org/downloads/beta/stunnel-5.74b1.tar.gz

**Pull request closed without merging**
